version: "3"

services:

  mosquitto:
    container_name: obscura_mosquitto
    build: ./mosquitto
    networks:
      - obscura
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data 
      - mosquitto_config:/mosquitto/config
      - mosquitto_log:/mosquitto/log
    restart: on-failure

  nodered:
    container_name: obscura_nodered
    build: ./nodered
    networks:
      - obscura
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data 
    restart: on-failure

  influxdb:
    container_name: obscura_influxdb
    image: "influxdb"
    networks:
      - obscura
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb 
    restart: on-failure

  grafana:
    container_name: obscura_grafana
    image: "grafana/grafana:9.4.7"
    networks:
      - obscura
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    restart: on-failure

volumes:
  nodered:
  influxdb:
  grafana:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log:

networks:
  obscura:
